declare module 'react-dev-utils/openBrowser'
declare module 'react-dev-utils/WebpackDevServerUtils'
declare module 'react-dev-utils/clearConsole'
declare module 'react-dev-utils/formatWebpackMessages'
declare module 'react-dev-utils/errorOverlayMiddleware'
